### ISSUE TITLE
No authentication used when downloading dependencies

### ISSUE THREAD

**Issue by UnaiUribarri-TomTom** [sbt/sbt-protobuf#166]
sbt-protobuf tries to download protobuf Maven package from my private repo but does not use the credentials configured in sbt.

```
[info] Compiling schema /Users/i/src/main/protobuf/wire.proto
[debug] protoc options:
[debug] 	--java_out=/Users/i/target/src_managed/main/compiled_protobuf
[info] Compiling schema /Users/i/src/main/protobuf/wire.proto
protoc-jar: protoc version: com.google.protobuf:protoc:3.25.0, detected platform: osx-aarch_64 (mac os x/aarch64)
[error] java.lang.RuntimeException: error occurred while compiling protobuf files: Server returned HTTP response code: 401 for URL: https://artifactory.example.com/artifactory/main-repo/com/google/protobuf/protoc/maven-metadata.xml
[error] 	at sbtprotobuf.ScopedProtobufPlugin.executeProtoc(ProtobufPlugin.scala:112)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.compile(ProtobufPlugin.scala:128)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.$anonfun$sourceGeneratorTask$3(ProtobufPlugin.scala:170)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:81)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:154)
[error] 	at sbt.util.Difference.apply(Tracked.scala:415)
[error] 	at sbt.util.Difference.apply(Tracked.scala:395)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:150)
[error] 	at sbt.util.Difference.apply(Tracked.scala:415)
[error] 	at sbt.util.Difference.apply(Tracked.scala:390)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:149)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.$anonfun$sourceGeneratorTask$1(ProtobufPlugin.scala:172)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://artifactory.example.com/artifactory/main-repo/com/google/protobuf/protoc/maven-metadata.xml
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[error] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[error] 	at com.github.os72.protocjar.Protoc.downloadFile(Protoc.java:333)
[error] 	at com.github.os72.protocjar.Protoc.downloadProtoc(Protoc.java:270)
[error] 	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:220)
[error] 	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:184)
[error] 	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:77)
[error] 	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:55)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.$anonfun$projectSettings$9(ProtobufPlugin.scala:67)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.$anonfun$projectSettings$9$adapted(ProtobufPlugin.scala:67)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.executeProtoc(ProtobufPlugin.scala:110)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.compile(ProtobufPlugin.scala:128)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.$anonfun$sourceGeneratorTask$3(ProtobufPlugin.scala:170)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:81)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:154)
[error] 	at sbt.util.Difference.apply(Tracked.scala:415)
[error] 	at sbt.util.Difference.apply(Tracked.scala:395)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:150)
[error] 	at sbt.util.Difference.apply(Tracked.scala:415)
[error] 	at sbt.util.Difference.apply(Tracked.scala:390)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:149)
[error] 	at sbtprotobuf.ScopedProtobufPlugin.$anonfun$sourceGeneratorTask$1(ProtobufPlugin.scala:172)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] (Protobuf / protobufGenerate) error occurred while compiling protobuf files: Server returned HTTP response code: 401 for URL: https://artifactory.example.com/artifactory/main-repo/com/google/protobuf/protoc/maven-metadata.xml
```

Contents of project/plugins.sbt
```
addSbtPlugin("com.github.sbt" % "sbt-protobuf" % "0.7.2")
```

Disabling the load of sbt-protobuf plugin and putting a direct dependency on  ```"com.google.protobuf" % "protoc" % "3.25.0" % Compile``` downloads the dependency correctly (but obviously fails because of missing compiled_protobuf sources.

**Comment by UnaiUribarri-TomTom** [comment]
Also, it is contacting a repository that is not configured in `build.sbt` but in ~/.m2/settings.xml, and it is not using the user/password specified in the servers section, which is working in other Maven projects I work in.

**Comment by UnaiUribarri-TomTom** [comment]
The root problem is that repo os72/protoc-jar does not support authenticated mirrors for maven-central.
After commenting out the maven-central mirror, everything worked correctly.
