### ISSUE TITLE
cross build for sbt 1.0

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-protobuf#51]

**Comment by xuwei-k** [comment]
WIP

- https://github.com/xuwei-k/sbt-protobuf/commit/fbe44023e55e9d33385382b396b0aa4a944e7bee
- https://travis-ci.org/xuwei-k/sbt-protobuf/jobs/249321147


some tests fail

- https://github.com/xuwei-k/sbt-protobuf/blob/fbe44023e55e9d33385382b396b0aa4a944e7bee/src/sbt-test/sbt-protobuf/basic/test#L18
- https://github.com/xuwei-k/sbt-protobuf/blob/fbe44023e55e9d33385382b396b0aa4a944e7bee/src/sbt-test/sbt-protobuf/task-scoped/test#L30


These tests introduced in https://github.com/sbt/sbt-protobuf/pull/42

Did you change the `FileFunction` behavior since sbt 1.0? or am I something wrong? /cc @eed3si9n

- https://github.com/sbt/sbt/blob/v0.13.15/cache/tracking/src/main/scala/sbt/Tracked.scala#L231
- https://github.com/sbt/util/blob/v1.0.0-M24/util-tracking/src/main/scala/sbt/util/FileFunction.scala


```
[error] x sbt-protobuf / basic 
sbt.internal.scripted.TestException: {line 18}  Command failed
	at sbt.internal.scripted.ScriptRunner.processStatement$1(ScriptRunner.scala:25)
	at sbt.internal.scripted.ScriptRunner.$anonfun$apply$3(ScriptRunner.scala:40)
	at sbt.internal.scripted.ScriptRunner.$anonfun$apply$3$adapted(ScriptRunner.scala:40)
	at sbt.internal.scripted.ScriptRunner$$Lambda$2056/2132627513.apply(Unknown Source)
	at scala.Function$.$anonfun$tupled$1(Function.scala:77)
	at scala.Function$$$Lambda$1982/1682156917.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at sbt.internal.scripted.ScriptRunner.apply(ScriptRunner.scala:40)
	at sbt.test.BatchScriptRunner.apply(BatchScriptRunner.scala:16)
	at sbt.test.ScriptedTests.$anonfun$commonRunTest$5(ScriptedTests.scala:271)
	at sbt.test.ScriptedTests$$Lambda$1993/1166957830.apply(Unknown Source)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at sbt.test.ScriptedTests.commonRunTest(ScriptedTests.scala:266)
	at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$5(ScriptedTests.scala:59)
	at sbt.test.ScriptedTests$$Lambda$1990/1092915911.apply(Unknown Source)
	at sbt.test.ScriptedTests.runOrHandleDisabled(ScriptedTests.scala:224)
	at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$4(ScriptedTests.scala:61)
	at sbt.test.ScriptedTests$$Lambda$1963/1654474024.apply(Unknown Source)
	at sbt.internal.io.Resources.readWrite$1(Resources.scala:57)
	at sbt.internal.io.Resources.$anonfun$readWriteResourceDirectory$1(Resources.scala:59)
	at sbt.internal.io.Resources$$Lambda$1964/568526183.apply(Unknown Source)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:331)
	at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:59)
	at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:47)
	at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$3(ScriptedTests.scala:53)
	at sbt.test.ScriptedTests$$Lambda$1961/352727436.apply(Unknown Source)
	at sbt.test.ScriptedRunner.$anonfun$runAll$1(ScriptedTests.scala:379)
	at sbt.test.ScriptedRunner$$Lambda$1962/1067223704.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$Lambda$176/1561875227.apply(Unknown Source)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at sbt.test.ScriptedRunner.runAll(ScriptedTests.scala:379)
	at sbt.test.ScriptedRunner.run(ScriptedTests.scala:334)
	at sbt.test.ScriptedRunner.run(ScriptedTests.scala:317)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at $41a6039767609d1ac61b$$anonfun$$sbtdef$1$$anonfun$apply$1$$anonfun$apply$2.apply(/home/travis/build/xuwei-k/sbt-protobuf/build.sbt:47)
	at $41a6039767609d1ac61b$$anonfun$$sbtdef$1$$anonfun$apply$1$$anonfun$apply$2.apply(/home/travis/build/xuwei-k/sbt-protobuf/build.sbt:38)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Test script error: File(s) did not exist: [ /tmp/sbt_f3471558/basic/target/scala-2.11/src_managed/main/compiled_protobuf/test/Test2.java ]
	at scala.sys.package$.error(package.scala:27)
	at sbt.internal.scripted.FileCommands.scriptError(FileCommands.scala:45)
	at sbt.internal.scripted.FileCommands.exists(FileCommands.scala:76)
	at sbt.internal.scripted.FileCommands.$anonfun$commandMap$3(FileCommands.scala:19)
	at sbt.internal.scripted.FileCommands.$anonfun$commandMap$3$adapted(FileCommands.scala:19)
	at sbt.internal.scripted.FileCommands$$Lambda$2081/921843161.apply(Unknown Source)
	at sbt.internal.scripted.FileCommands$CommandBuilder.$anonfun$nonEmpty$1(FileCommands.scala:103)
	at sbt.internal.scripted.FileCommands$CommandBuilder.$anonfun$nonEmpty$1$adapted(FileCommands.scala:99)
	at sbt.internal.scripted.FileCommands$CommandBuilder$$Lambda$2079/641573932.apply(Unknown Source)
	at sbt.internal.scripted.FileCommands.$anonfun$apply$1(FileCommands.scala:40)
	at sbt.internal.scripted.FileCommands.$anonfun$apply$1$adapted(FileCommands.scala:40)
	at sbt.internal.scripted.FileCommands$$Lambda$2096/1973161522.apply(Unknown Source)
	at scala.Option.map(Option.scala:146)
	at sbt.internal.scripted.FileCommands.apply(FileCommands.scala:40)
	at sbt.internal.scripted.BasicStatementHandler.apply(StatementHandler.scala:18)
	at sbt.internal.scripted.BasicStatementHandler.apply$(StatementHandler.scala:18)
	at sbt.internal.scripted.FileCommands.apply(FileCommands.scala:13)
	at sbt.internal.scripted.FileCommands.apply(FileCommands.scala:13)
	at sbt.internal.scripted.ScriptRunner.processStatement$1(ScriptRunner.scala:18)
```

```
[error] x sbt-protobuf / task-scoped 
sbt.internal.scripted.TestException: {line 30}  Command failed
	at sbt.internal.scripted.ScriptRunner.processStatement$1(ScriptRunner.scala:25)
	at sbt.internal.scripted.ScriptRunner.$anonfun$apply$3(ScriptRunner.scala:40)
	at sbt.internal.scripted.ScriptRunner.$anonfun$apply$3$adapted(ScriptRunner.scala:40)
	at sbt.internal.scripted.ScriptRunner$$Lambda$2056/2132627513.apply(Unknown Source)
	at scala.Function$.$anonfun$tupled$1(Function.scala:77)
	at scala.Function$$$Lambda$1982/1682156917.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at sbt.internal.scripted.ScriptRunner.apply(ScriptRunner.scala:40)
	at sbt.test.BatchScriptRunner.apply(BatchScriptRunner.scala:16)
	at sbt.test.ScriptedTests.$anonfun$commonRunTest$5(ScriptedTests.scala:271)
	at sbt.test.ScriptedTests$$Lambda$1993/1166957830.apply(Unknown Source)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at sbt.test.ScriptedTests.commonRunTest(ScriptedTests.scala:266)
	at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$5(ScriptedTests.scala:59)
	at sbt.test.ScriptedTests$$Lambda$1990/1092915911.apply(Unknown Source)
	at sbt.test.ScriptedTests.runOrHandleDisabled(ScriptedTests.scala:224)
	at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$4(ScriptedTests.scala:61)
	at sbt.test.ScriptedTests$$Lambda$1963/1654474024.apply(Unknown Source)
	at sbt.internal.io.Resources.readWrite$1(Resources.scala:57)
	at sbt.internal.io.Resources.$anonfun$readWriteResourceDirectory$1(Resources.scala:59)
	at sbt.internal.io.Resources$$Lambda$1964/568526183.apply(Unknown Source)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:331)
	at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:59)
	at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:47)
	at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$3(ScriptedTests.scala:53)
	at sbt.test.ScriptedTests$$Lambda$1961/352727436.apply(Unknown Source)
	at sbt.test.ScriptedRunner.$anonfun$runAll$1(ScriptedTests.scala:379)
	at sbt.test.ScriptedRunner$$Lambda$1962/1067223704.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$Lambda$176/1561875227.apply(Unknown Source)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at sbt.test.ScriptedRunner.runAll(ScriptedTests.scala:379)
	at sbt.test.ScriptedRunner.run(ScriptedTests.scala:334)
	at sbt.test.ScriptedRunner.run(ScriptedTests.scala:317)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at $41a6039767609d1ac61b$$anonfun$$sbtdef$1$$anonfun$apply$1$$anonfun$apply$2.apply(/home/travis/build/xuwei-k/sbt-protobuf/build.sbt:47)
	at $41a6039767609d1ac61b$$anonfun$$sbtdef$1$$anonfun$apply$1$$anonfun$apply$2.apply(/home/travis/build/xuwei-k/sbt-protobuf/build.sbt:38)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Test script error: File(s) did not exist: [ /tmp/sbt_4c0997af/task-scoped/target/scala-2.11/src_managed/main/compiled_protobuf/test/Test2.java ]
	at scala.sys.package$.error(package.scala:27)
	at sbt.internal.scripted.FileCommands.scriptError(FileCommands.scala:45)
	at sbt.internal.scripted.FileCommands.exists(FileCommands.scala:76)
	at sbt.internal.scripted.FileCommands.$anonfun$commandMap$3(FileCommands.scala:19)
	at sbt.internal.scripted.FileCommands.$anonfun$commandMap$3$adapted(FileCommands.scala:19)
	at sbt.internal.scripted.FileCommands$$Lambda$2081/921843161.apply(Unknown Source)
	at sbt.internal.scripted.FileCommands$CommandBuilder.$anonfun$nonEmpty$1(FileCommands.scala:103)
	at sbt.internal.scripted.FileCommands$CommandBuilder.$anonfun$nonEmpty$1$adapted(FileCommands.scala:99)
	at sbt.internal.scripted.FileCommands$CommandBuilder$$Lambda$2079/641573932.apply(Unknown Source)
	at sbt.internal.scripted.FileCommands.$anonfun$apply$1(FileCommands.scala:40)
	at sbt.internal.scripted.FileCommands.$anonfun$apply$1$adapted(FileCommands.scala:40)
	at sbt.internal.scripted.FileCommands$$Lambda$2096/1973161522.apply(Unknown Source)
	at scala.Option.map(Option.scala:146)
	at sbt.internal.scripted.FileCommands.apply(FileCommands.scala:40)
	at sbt.internal.scripted.BasicStatementHandler.apply(StatementHandler.scala:18)
	at sbt.internal.scripted.BasicStatementHandler.apply$(StatementHandler.scala:18)
	at sbt.internal.scripted.FileCommands.apply(FileCommands.scala:13)
	at sbt.internal.scripted.FileCommands.apply(FileCommands.scala:13)
	at sbt.internal.scripted.ScriptRunner.processStatement$1(ScriptRunner.scala:18)
	... 59 more
```

**Comment by xuwei-k** [comment]
Ah, sorry maybe https://github.com/sbt/sbt/pull/2613.
I should add `crossScalaVersions += "2.11.11"` or use `!` (force set scalaVersion)

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-protobuf/commit/b3574f2ba07a0de27dbede836bafbc38f7baa500
0.6.1 released
